rules:
  # Original rules
  - name: "high_closing_costs"
    type: "calculated_percentage"
    numerator_pattern: "(?:Total Closing Costs|closing costs?).*?\\\\$([0-9,]+(?:\\\\.[0-9]{2})?)"
    denominator_pattern: "Loan Amount.*?\\\\$([0-9,]+(?:\\\\.[0-9]{2})?)"
    threshold: 4.0
    operator: ">"
    message: "High closing costs detected: {percentage}% of loan amount (${numerator}) - typical range is 2-3%"
    
  - name: "excessive_loan_amount"
    type: "numeric_threshold"
    pattern: "(?:loan amount|principal).*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    threshold: 500000
    operator: ">"
    message: "Loan amount exceeds threshold: ${value}"
    
  - name: "missing_title_insurance"
    type: "regex_absence"
    pattern: "title insurance"
    message: "Title insurance not found in document"
    
  - name: "missing_home_inspection"
    type: "regex_absence"
    pattern: "(?:home inspection|property inspection)"
    message: "Home inspection not mentioned in closing documents"
    
  - name: "suspicious_wire_transfer"
    type: "regex_amount"
    pattern: "wire transfer.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    threshold: 10000
    operator: ">"
    message: "Large wire transfer detected: ${value}"
    
  - name: "high_interest_rate"
    type: "numeric_threshold"
    pattern: "(?:interest rate|apr).*?([0-9]+(?:\\.[0-9]{1,3})?)%"
    threshold: 7.0
    operator: ">"
    message: "High interest rate detected: {value}%"

  # Enhanced predatory practice detection rules
  - name: "excessive_origination_percentage"
    type: "calculated_percentage"
    numerator_pattern: "(?:Origination|\\. \\. \\. \\$)([0-9,]+(?:\\.[0-9]{2})?)(?:\\s|$)"
    denominator_pattern: "Loan Amount.*?\\\\$([0-9,]+(?:\\\\.[0-9]{2})?)"
    threshold: 1.5
    operator: ">"
    message: "Excessive origination fee: {percentage}% of loan amount (typical range: 0.5-1.5%)"

  - name: "missing_buyer_representation"
    type: "regex_presence"
    pattern: "Real Estate Broker \\(B\\).*?N/A"
    message: "No buyer agent representation found - you may lack independent advocacy"

  - name: "buyer_broker_marked_na"
    type: "regex_amount"
    pattern: "Real Estate Broker \\(B\\).*?N/A.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    threshold: 0
    operator: ">="
    message: "Buyer broker listed as N/A but charging fees - consider seeking independent representation"

  - name: "builder_captive_services"
    type: "cross_reference_pattern"
    primary_pattern: "Seller.*?([A-Z][A-Z\\s]+(?:HOMES?|BUILDER?|CONSTRUCTION))"
    secondary_patterns:
      - pattern: "Lender.*?([A-Z][A-Z\\s]+(?:MORTGAGE|LENDING|FINANCIAL))"
        service: "mortgage"
      - pattern: "Insurance.*?([A-Z][A-Z\\s]+(?:INSURANCE|ASSURANCE))"
        service: "insurance"
      - pattern: "Title.*?([A-Z][A-Z\\s]+(?:TITLE|ESCROW))"
        service: "title"
    fuzzy_match: true
    message: "⚠️ BUILDER CAPTIVE SERVICES: {primary} controls {services} - seek independent pricing comparison"

  - name: "expensive_loan_combination"
    type: "compound_rule"
    conditions:
      - pattern: "Interest Rate.*?([0-9]+(?:\\.[0-9]{1,3})?)%"
        threshold: 6.5
        operator: ">"
        value_name: "rate"
      - pattern: "Total Closing Costs.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
        threshold: 15000
        operator: ">"
        value_name: "fees"
    message: "⚠️ EXPENSIVE LOAN: High interest rate ({rate}%) + high closing costs (${fees}) - shop alternatives"

  - name: "zero_closing_costs_deception"
    type: "numeric_threshold"
    pattern: "(?:Total Closing Costs|Closing Costs).*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    threshold: 1000
    operator: ">"
    message: "⚠️ 'ZERO CLOSING COSTS' DECEPTION: Despite promises, you're paying ${value} in closing costs"


  # Critical document error detection rules
  - name: "loan_type_contradiction"
    type: "regex_presence"
    pattern: "Loan Type.*?Conventional.*?☑.*?FHA|Loan Type.*?FHA.*?☑.*?Conventional"
    message: "🚨 CRITICAL ERROR: Loan marked as both Conventional AND FHA - this is impossible and indicates document errors"

  - name: "fha_mip_on_conventional_loan"
    type: "regex_presence"
    pattern: "Loan Type.*?Conventional.*FHA UP FRONT MIP.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "🚨 BILLING ERROR: FHA MIP charged on Conventional loan - you shouldn't pay this fee"

  - name: "demand_feature_on_purchase_loan"
    type: "regex_presence"
    pattern: "Purpose\\s+Purchase.*has a demand feature"
    message: "🚨 DANGEROUS LOAN FEATURE: Demand feature allows lender to call full balance due at any time - extremely risky for purchase loans"

  - name: "negative_amortization_error"
    type: "regex_presence"
    pattern: "scheduled to make monthly payments that do not pay all of the interest"
    message: "⚠️ DOCUMENT ERROR: Negative amortization checked but this contradicts normal loan payment structure - verify loan terms"

  - name: "extreme_total_interest_percentage"
    type: "numeric_threshold"
    pattern: "Total Interest Percentage \\(TIP\\).*?([0-9]+(?:\\.[0-9]+)?)%"
    threshold: 100.0
    operator: ">"
    message: "🚨 PREDATORY LOAN: {value}% Total Interest Percentage means you'll pay more in interest than the original loan amount"

  - name: "extreme_finance_charge_ratio"
    type: "calculated_percentage"
    numerator_pattern: "Finance Charge.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    denominator_pattern: "Loan Amount.*?\\\\$([0-9,]+(?:\\\\.[0-9]{2})?)"
    threshold: 100.0
    operator: ">"
    message: "🚨 PREDATORY LOAN: Finance charge is {percentage}% of loan amount - this is an extremely expensive loan"

  - name: "missing_mortgage_insurance_escrow_details"
    type: "regex_absence"
    pattern: "Mortgage Insurance Premium \\([0-9]+ mo\\)"
    message: "⚠️ INCOMPLETE DOCUMENT: Mortgage Insurance escrow details missing - verify proper funding and monthly amounts"

  - name: "high_apr_vs_interest_rate_spread"
    type: "compound_rule"
    conditions:
      - pattern: "Interest Rate\\s+([0-9]+(?:\\.[0-9]+)?)%"
        threshold: 0
        operator: ">="
        value_name: "rate"
      - pattern: "Annual Percentage Rate \\(APR\\).*?([0-9]+(?:\\.[0-9]+)?)%"
        threshold: 0
        operator: ">="
        value_name: "apr"
    message: "⚠️ HIGH FEES: APR ({apr}%) significantly higher than interest rate ({rate}%) indicates expensive loan costs and fees"

  # Purchase price and loan amount verification rules
  - name: "purchase_price_mismatch"
    type: "context_comparison"
    comparison_type: "purchase_price"
    pattern: "(?:Purchase Price|Sale Price).*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    tolerance_percentage: 1.0
    message: "🚨 PRICE MISMATCH: Expected ${expected} but document shows ${actual} ({difference} difference)"

  - name: "loan_amount_mismatch"
    type: "context_comparison"
    comparison_type: "loan_amount"
    pattern: "Loan Amount.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    tolerance_percentage: 1.0
    message: "🚨 LOAN AMOUNT MISMATCH: Expected ${expected} but document shows ${actual} ({difference} difference)"

  # Unexpected borrower-paid items (should be paid by seller/builder in TX new construction)
  - name: "buyer_paying_title_insurance"
    type: "regex_presence"
    pattern: "Owner's Title Insurance.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "⚠️ UNEXPECTED CHARGE: You're paying for Owner's Title Insurance (${1}) - typically paid by seller in TX"

  - name: "buyer_paying_survey_fee"
    type: "regex_presence"
    pattern: "Survey.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "⚠️ UNEXPECTED CHARGE: You're paying for property survey (${1}) - typically paid by seller in TX new construction"

  - name: "buyer_paying_settlement_fee"
    type: "regex_presence"
    pattern: "Settlement.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "⚠️ UNEXPECTED CHARGE: You're paying settlement fee (${1}) - often covered by builder in TX"

  - name: "buyer_paying_doc_prep"
    type: "regex_presence"
    pattern: "Document Preparation.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "⚠️ UNEXPECTED CHARGE: You're paying document prep fee (${1}) - typically lender/title company cost"

  - name: "buyer_paying_notary_fee"
    type: "regex_presence"
    pattern: "Notary.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "⚠️ UNEXPECTED CHARGE: You're paying notary fee (${1}) - typically covered by title company"

  - name: "buyer_paying_courier_fee"
    type: "regex_presence"
    pattern: "Courier.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    message: "⚠️ UNEXPECTED CHARGE: You're paying courier fee (${1}) - typically title company responsibility"

  - name: "excessive_title_fees"
    type: "numeric_threshold"
    pattern: "Title.*?Borrower.*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    threshold: 2000
    operator: ">"
    message: "🚨 EXCESSIVE TITLE FEES: You're paying ${value} in title fees - typical TX range is $1,200-$1,800"

  - name: "excessive_lender_fees"
    type: "calculated_percentage"
    numerator_pattern: "(?:Processing|Underwriting|Administration).*?\\$([0-9,]+(?:\\.[0-9]{2})?)"
    denominator_pattern: "Loan Amount.*?\\\\$([0-9,]+(?:\\\\.[0-9]{2})?)"
    threshold: 0.5
    operator: ">"
    message: "⚠️ HIGH LENDER FEES: Processing/admin fees are {percentage}% of loan - typical range is 0.1-0.3%"